### ISSUE TITLE
homepage design(authenticated page) / sherifatshe2 and ever / Product Design

### ISSUE THREAD

**Issue by Saad-Saheed** [zuri-training/Price-compare-project-team-21-Frontend#21]
TOP ITEMS IN ACCESSORIES (WITH BOXES REPRESENTING THE IMAGES, THE NAME OF THE BRAND, DESCRIPTION AND SELLER COMING IMMEDIATELY BELOW AND THE PRICE FOLLOWS)

**Comment by sherifatshe2** [comment]
Done!!!!

**Comment by EverObas** [comment]
Done
