### ISSUE TITLE
LIST OF TOP STORE / Ziggy, Buhari and Sunkanmi / Product Design

### ISSUE THREAD

**Issue by Saad-Saheed** [zuri-training/Price-compare-project-team-21-Frontend#25]
LIST OF TOP STORE / Ziggy, Buhari and Sunkanmi / Product Design

**Comment by Seunlijadu** [comment]
Latest update on my assigned tasks

https://www.figma.com/file/2Rm18o3n7a86AcfpdZgrYF/PriceBeta?node-id=458%3A1667
